using System;

namespace Resolink
{
    /// <summary>
    /// Data associated with a single control in Resolume
    /// </summary>
    [Serializable]
    public class ResolumeOscShortcut
    {
        /// <summary>
        /// An id generated by resolume.  Not actually used as a key here.
        /// </summary>
        public long UniqueId;
        
        /// <summary>
        /// The path the Resolume receives messages for this control at.
        /// Used as the persistent unique identifier for a control, since it doesn't change in Resolume.
        /// </summary
        public ShortcutPath Input;
        
        /// <summary>
        /// The path the Resolume outputs this message to, where Unity receives it.
        /// </summary>
        public ShortcutPath Output;
        
        /// <summary>
        /// All sub-targets for this path (if any)
        /// </summary>
        public SubTarget[] SubTargets;               
        
        /// <summary>
        /// The .Name of the data type
        /// </summary>
        public string TypeName;
    }
}